#ifndef WEATHER_FONT_H
#define WEATHER_FONT_H

#include <stdint.h>

#define WEATHER_FONT_GLYPH_WIDTH       24U
#define WEATHER_FONT_20_HEIGHT          20U
#define WEATHER_FONT_24_HEIGHT          24U
#define WEATHER_FONT_20_BYTES_PER_GLYPH 60U
#define WEATHER_FONT_24_BYTES_PER_GLYPH 72U
#define WEATHER_FONT_GLYPH_COUNT       49U

enum
{
    WEATHER_GLYPH_SUNNY = 0,
    WEATHER_GLYPH_OVERCAST = 1,
    WEATHER_GLYPH_SMALL = 2, WEATHER_GLYPH_MEDIUM = 3, WEATHER_GLYPH_BIG = 4,
    WEATHER_GLYPH_STORM = 5, WEATHER_GLYPH_RAIN = 6, WEATHER_GLYPH_SNOW = 7,
    WEATHER_GLYPH_MANY = 8, WEATHER_GLYPH_CLOUD = 9, WEATHER_GLYPH_FOG = 11,
    WEATHER_GLYPH_SHOWER = 42, WEATHER_GLYPH_THUNDER = 43,
    WEATHER_GLYPH_MIXED = 44, WEATHER_GLYPH_HAZE = 45,
    WEATHER_GLYPH_SAND = 46, WEATHER_GLYPH_DUST = 47,
    WEATHER_GLYPH_WIND = 48,
    WEATHER_GLYPH_SHANG = 12,
    WEATHER_GLYPH_HAI = 13,
    WEATHER_GLYPH_CITY = 14,
    WEATHER_GLYPH_ROOM = 15, WEATHER_GLYPH_INDOOR = 16,
    WEATHER_GLYPH_MOST = 17, WEATHER_GLYPH_HIGH = 18, WEATHER_GLYPH_LOW = 19,
    WEATHER_GLYPH_WEEK = 20, WEATHER_GLYPH_PERIOD = 21, WEATHER_GLYPH_ONE = 22,
    WEATHER_GLYPH_TWO = 23, WEATHER_GLYPH_THREE = 24, WEATHER_GLYPH_FOUR = 25,
    WEATHER_GLYPH_FIVE = 26, WEATHER_GLYPH_SIX = 27, WEATHER_GLYPH_DAY = 28,
    WEATHER_GLYPH_CONNECT = 29, WEATHER_GLYPH_LINK = 30, WEATHER_GLYPH_IN_PROGRESS = 31,
    WEATHER_GLYPH_SUCCESS = 32, WEATHER_GLYPH_MERIT = 33,
    WEATHER_GLYPH_FAILURE = 34, WEATHER_GLYPH_DEFEAT = 35,
    WEATHER_GLYPH_SMART = 36, WEATHER_GLYPH_CAN = 37, WEATHER_GLYPH_WEATHER = 38, WEATHER_GLYPH_AIR = 39,
    WEATHER_GLYPH_TIME = 40, WEATHER_GLYPH_CLOCK = 41
};

extern const uint8_t weather_font_24x20[WEATHER_FONT_GLYPH_COUNT]
                                     [WEATHER_FONT_20_BYTES_PER_GLYPH];
extern const uint8_t weather_font_24x24[WEATHER_FONT_GLYPH_COUNT]
                                     [WEATHER_FONT_24_BYTES_PER_GLYPH];

void WeatherFont_DrawText20(uint16_t x, uint16_t y, const uint8_t *glyphs,
                            uint16_t count, uint16_t text_color,
                            uint16_t back_color);
void WeatherFont_DrawText24(uint16_t x, uint16_t y, const uint8_t *glyphs,
                            uint16_t count, uint16_t text_color,
                            uint16_t back_color);

#endif
